[package]
name = "spacebar"
version = "0.1.0"
authors = ["diego"]

[dependencies]
rocket = "0.2.0"
rocket_codegen = "0.2.0"
postgres="0.13"
rand = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"