[package]
name = "spacebar"
version = "0.1.0"
authors = ["Chad Baxter"]

[dependencies]
clap = "2.29.4"
clipboard = "0.4.2"
rand = "0.4.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.27"
spinners = "0.4.0"
